### ISSUE TITLE
maybe need a switch to control whether add git repo and edit link.

### ISSUE THREAD

**Issue by GuidianLiang** [YvesCoding/antdsite#11]
our workbench is forbidden to connect outside network, but theme config need to connect github. we hava to remove avatar attribute from resolveoptions sourcr code, but i it is unfriendly for upgrade version in future.

**Comment by wangyi7099** [comment]
马上改进，今晚发布

**Comment by wangyi7099** [comment]
试试0.1.9 `themeConfig.showAvatarList` 设置`为 false` 即可。
