### ISSUE TITLE
最近 antd 升级到 4.x 之后，样式引用出现了问题

### ISSUE THREAD

**Issue by yesixuan** [YvesCoding/antdsite#16]
最近 antd 升级到 4.x 之后，样式引用出现了问题
@import '~antd/lib/style/v2-compatible-reset.less';
^
Can't resolve 'antd/lib/style/v2-compatible-reset.less' in xxx

**Comment by wangyi7099** [comment]
好的 我解决下

**Comment by wangyi7099** [comment]
try @rcpress/cli@0.1.11

**Comment by wangyi7099** [comment]
0.11.2 我先把antd回退到3.x  后期会针对4.x做兼容性优化
