### ISSUE TITLE
配置 base: '/rcpress-demo/' 这个选项之后，开发模式预览报错

### ISSUE THREAD

**Issue by yesixuan** [YvesCoding/antdsite#17]
![image](https://user-images.githubusercontent.com/22050621/76181391-d6ffdf00-61fb-11ea-985d-8a79316df48f.png)

![image](https://user-images.githubusercontent.com/22050621/76181519-57bedb00-61fc-11ea-8562-dee8f1dc4aea.png)

**Comment by wangyi7099** [comment]
去掉开头或者结尾处的 /

**Comment by yesixuan** [comment]
试过了，不管是去掉前面的 / 还是后面的 /
都还是报同样的错误

**Comment by wangyi7099** [comment]
试试 0.1.13 
base为 /rcpress-demo
