### ISSUE TITLE
rcpress0.1.9版本打包后的文件通过github pages部署，点击搜索栏会导致页面白屏

### ISSUE THREAD

**Issue by PockyRayzz** [YvesCoding/antdsite#33]
## 版本号
 - 0.1.9

## 打包命令
 - rcpress generate
 - rcpress build

## 截图
![image](https://user-images.githubusercontent.com/29441283/89186297-2b9e5f00-d5ce-11ea-8cc8-d3b424fe4341.png)

**Comment by wangyi7099** [comment]
f12报错了没

**Comment by PockyRayzz** [comment]
> f12报错了没

![image](https://user-images.githubusercontent.com/29441283/89244792-f891b500-d639-11ea-8e13-254120762ad5.png)
