### ISSUE TITLE
Questions/comparison regarding VuePress 

### ISSUE THREAD

**Issue by berot3** [YvesCoding/antdsite#5]
Thank you but I have 4 questions, since I couldn’t really get warm with VuePress:

1. is it possible to get full-text-search that does not rely on some cloud-service?

2. how about automatic sidebar-generation, so that one does not have to enter every new page manually! (MkDocs has a great solution that also allows re-arranging/manipulation)

3. what about other markdown-parser like remarkable or markdown-it, can those be used?

4. would it be possible to use your great theme/design in VuePress?

**Comment by wangyi7099** [comment]
> is it possible to get full-text-search that does not rely on some cloud-service?

 Yes, but the bundle code will be too large. And I don't want to make bundle code too large. Or treat it as optional?

> how about automatic sidebar-generation, so that one does not have to enter every new page manually! (MkDocs has a great solution that also allows re-arranging/manipulation)

Good idea! Maybe we should pick this feature.

> what about other markdown-parser like remarkable or markdown-it, can those be used?

No. We currently use gatsbyJs and its build-in markdown plugin : gatsby-transfrom-remark. So we will not change the markdown parser.

> would it be possible to use your great theme/design in VuePress?

Yes, IMO, you can use this awesome UI framework [ant-design-vue](https://github.com/vueComponent/ant-design-vue) to get the same ui.

**Comment by berot3** [comment]
thanks for replying so promptly! 😄
