### ISSUE TITLE
配置base无效

### ISSUE THREAD

**Issue by fantasticsoul** [YvesCoding/antdsite#6]
在.antdsite里配置base无效，尴尬，能帮忙看看吗？我之前的站点doc是用docusaurus搭建的，看到了你这antdsite觉得不错，就像换下试试，下面这个链接是我部署到git page的连接，点击右上角guide导航按钮，就报错404，你可以邮件检查dom元素看到a标签里并不是`/concent-doc/guide`而是`/guide`
https://concentjs.github.io/concent-doc/

可以我的确配置了base了，下面链接是配置base的地方
https://github.com/concentjs/concent-doc/blob/master/website/.antdsite/config.js

我把源码都放到website下，构建后全部拷贝到顶层根目录，方便gitpage直接以根目录做首页。

请问我哪里搞错了吗？

**Comment by wangyi7099** [comment]
参考这个 https://github.com/YvesCoding/antdsite/blob/master/packages/docs/package.json

build 和 develop命令后面加上 `--prefix-paths` 参数

**Comment by fantasticsoul** [comment]
如果我输入以下链接，倒是能访问，但是左侧的折叠导航栏却不能展开了
https://concentjs.github.io/concent-doc/guide/introduction/

**Comment by fantasticsoul** [comment]
谢谢，一切正常了，可是又出现了一个新的问题
点击header的icon图标，访问的是
https://concentjs.github.io/concent-doc/concent-doc/
导致404，这是为什么呢

**Comment by fantasticsoul** [comment]
难道配置文件里head还需要什么额外的处理吗？

**Comment by wangyi7099** [comment]
这可能是个bug 我研究下

**Comment by fantasticsoul** [comment]
好的，还有个问题，我本地npm run start的时候，还必须要先去config里把base注释掉，能通过什么方式不需要去手动注释掉base吗？本地开发是base不起效，只是构建时加上--prefix-paths 参数让其起效

**Comment by wangyi7099** [comment]
不加 `--prefix-paths` 即使你设置了base也是无效的。

`0.12.10` 修复了 logo的bug了
