### ISSUE TITLE
无法启动spa

### ISSUE THREAD

**Issue by harry0071** [YvesCoding/antdsite#7]
本人电脑：mac系统
运行rcpress dev，报错：env: node\r: No such file or directory
这是什么情况？

![99F63341-C64E-4B7F-AC35-71EB3A65BF6F.png](https://i.loli.net/2019/11/21/dfzkyWan7YX9P2M.png)

**Comment by wangyi7099** [comment]
mac下的坑。。 哎   换行符导致的，我马上修复一直

**Comment by wangyi7099** [comment]
@rcpress/cli 0.1.6 应该可以了。
