### ISSUE TITLE
mac系统运行rcpress build没有生成打包文件

### ISSUE THREAD

**Issue by harry0071** [YvesCoding/antdsite#9]
### **运行rcpress build后，目录里没有出现打包后的文件**

![9.png](https://i.loli.net/2019/11/26/3uDlwvW1Eao4zYy.png)

![123.png](https://i.loli.net/2019/11/26/wjxR1rPY68MWXnL.png)

**Comment by wangyi7099** [comment]
generate 能行不？

**Comment by wangyi7099** [comment]
@rcpress/cli@0.1.7
